<?php
return [
 'PROJECT_NAME' => 'TIJARA',
 'DATE_FORMAT'  => 'Y-m-d H:i:s',
 'RECORDS_SHOW_PER_PAGE' => 10,
 'CONTACT_ENQUIRY_EMAIL' => '',
 'CONTACT_ENQUIRY_EMAIL_CC' => '',
 'COMMON_FILE_FOLDER' => '/public/uploads/',
 'COMMON_FILE_URL' => '/uploads/',
 'ORDER_STATUS' => ['PENDING','PROCESSING','COLLECTED','COMPLETE','FAILED'],
 'ARAMEX_GET_RATE_URL' => 'https://nservice.aramex.co.za/Json/JsonV1/GetRate',
 'ARAMEX_WAYBILL_URL' => 'https://nservice.aramex.co.za/Json/JsonV1/SubmitWaybill',
 'ARAMEX_EMAIL' => null,
 'ARAMEX_PASSWORD' => null,
 'ARAMEX_ACCOUNT' => null,
 #'PAYGATEID' => '10011072130',
 #'PAYGATESECRET' => 'secret',
 #'PAYGATEID' => '1038008100011',
 #'PAYGATESECRET' => 'ZtjR4tACuaQWscDbTkylhxEf',
 'Products_limits'=>'20',
 'Services_limits'=>'20',
 'review_limits'=>'10',
 'buyer_product'=>'12',
 'Front_Products_limits'=>'10',
 'Front_Services_limits'=>'10',
 'Popular_Product_limits'=>'5',
];
